#!/usr/bin/env python3
"""Generate the evidence index's contents block, or check it is current.

The index is nearly two thousand lines and a reader arriving at it has to
scroll to find out what is in it. That is a real cost for the one audience it
exists for -- someone deciding whether a claim is evidenced -- and it grows
every time a finding is recorded.

The block is generated rather than maintained, because a hand-written contents
list on a file that grows weekly is a contents list that is wrong by the
second week. check_docs.py runs this with --check, so a new section that is
not in the block fails the documentation gate rather than quietly not being
listed.
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "production" / "EVIDENCE_INDEX.md"
START = "<!-- contents: generated by scripts/toc.py, do not edit by hand -->"
END = "<!-- end contents -->"


def anchor(heading: str) -> str:
    slug = heading.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    return re.sub(r"[\s_]+", "-", slug).strip("-")


def build(text: str) -> str:
    findings, entries = [], []
    for line in text.splitlines():
        if not line.startswith("## "):
            continue
        heading = line[3:].strip()
        if heading.lower().startswith("contents"):
            continue
        row = f"- [{heading}](#{anchor(heading)})"
        (findings if heading.startswith("FINDING") else entries).append(row)
    parts = [START, "", "## Contents", ""]
    if findings:
        parts += [
            "**Findings** — defects this project made and recorded, kept here rather",
            "than in a tracker because each one is evidence about how far the",
            "surrounding claims can be trusted.", "",
        ] + findings + [""]
    parts += ["**Evidence**", ""] + entries + ["", END]
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the block is missing or stale, and change nothing")
    arguments = parser.parse_args()

    text = INDEX.read_text()
    body = text
    if START in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        body = head + tail.lstrip("\n")
    wanted = build(body)

    if arguments.check:
        if START not in text:
            print(f"{INDEX.name} has no contents block; run scripts/toc.py", file=sys.stderr)
            return 1
        current = START + text.split(START, 1)[1].split(END, 1)[0] + END
        if current.strip() != wanted.strip():
            print(f"{INDEX.name}'s contents block is stale; run scripts/toc.py",
                  file=sys.stderr)
            return 1
        return 0

    # Insert after the opening paragraph, before the first section.
    first = body.index("\n## ")
    INDEX.write_text(body[:first] + "\n" + wanted + "\n" + body[first:])
    print(f"wrote the contents block into {INDEX.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
