#!/usr/bin/env python3
"""Self-tests for the preregistered analysis harness.

An analysis tool that silently stops detecting differences is worse than no
tool, so these check both directions: that identical worlds pass and that
each kind of difference the preregistration names is actually caught.
"""

import importlib.util
import os
import pathlib
import subprocess
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).parent))

spec = importlib.util.spec_from_file_location(
    "twa", pathlib.Path(__file__).with_name("two-world-analysis.py")
)
twa = importlib.util.module_from_spec(spec)
spec.loader.exec_module(twa)

import capture

failures = []


def check(name, condition):
    if condition:
        print(f"ok   {name}")
    else:
        print(f"FAIL {name}")
        failures.append(name)


# Capture parsing. tcpdump is not available in every environment the harness
# runs in, so the line parser is exercised directly against recorded output.
CAPTURE = """reading from file world-a.pcap, link-type EN10MB (Ethernet)
1712345678.100000 IP 10.0.0.2.4200 > 10.0.0.3.4200: UDP, length 1200
1712345678.150000 IP 10.0.0.2.4200 > 10.0.0.4.4200: UDP, length 1200
1712345678.200000 IP6 fd00::2.4200 > fd00::3.4200: UDP, length 1200
1712345678.250000 vlan 7, p 0, IP 10.0.0.2.4200 > 10.0.0.3.4200: UDP, length 1200
"""
parsed_times, parsed_sizes, parsed_destinations, parsed_sources = capture.parse_tcpdump(CAPTURE)
check("parser reads every packet line", len(parsed_times) == 4)
check("parser reads the IPv6 form", parsed_destinations[2] == "fd00::3.4200")
# A VLAN-tagged capture puts four tokens between the timestamp and the IP
# token. A prefix pattern that allows only two silently drops every tagged
# packet, which on the cadence gate means an oversized cell passes unseen.
check("parser reads the VLAN-tagged form",
      parsed_destinations[3] == "10.0.0.3.4200" and parsed_sources[3] == "10.0.0.2.4200")
check("parser reads sizes", parsed_sizes == [1200] * 4)

# Captures reach the rule two ways: as pcap files, and as text already in
# tcpdump's format, which is what the in-process wire campaign writes. Running
# tcpdump over the second kind fails, and that failure used to surface as a
# rejection -- the rule reporting that two worlds differed when it had never
# read them. The format is decided from the file's own first four bytes.
with tempfile.TemporaryDirectory() as workspace:
    text_path = pathlib.Path(workspace) / "already-rendered.txt"
    text_path.write_text(CAPTURE)
    check("a rendered text capture is not mistaken for a pcap",
          not capture.is_pcap(str(text_path)))
    times, sizes, _, _ = capture.read_capture(str(text_path))
    check("a rendered text capture is read without tcpdump",
          len(times) == 4 and sizes == [1200] * 4)

    pcap_path = pathlib.Path(workspace) / "binary.pcap"
    pcap_path.write_bytes(b"\xd4\xc3\xb2\xa1" + b"\x00" * 32)
    check("a libpcap file is recognised as binary", capture.is_pcap(str(pcap_path)))

# An unrecognised line must stop the run. Silently skipping it would drop
# packets, and a dropped packet makes two worlds look more alike, not less.
try:
    capture.parse_tcpdump(CAPTURE + "1712345678.300000 IP 10.0.0.2 > 10.0.0.3: ICMP echo\n")
    check("parser rejects an unparsed line", False)
except capture.CaptureError:
    check("parser rejects an unparsed line", True)

# Preamble and trailer lines are not packets and must not be errors either.
capture.parse_tcpdump(
    "tcpdump: verbose output suppressed\nlistening on eth0\n4 packets captured\n"
)
check("parser tolerates tcpdump preamble and trailer lines", True)

# The Go wire campaign (nomad-testnet live/wire) renders its captures in this
# same format so that one decision rule judges both a Go campaign and a real
# pcap. The committed sample is regenerated by a test in that package, so a
# format change on either side fails on the other.
GO_SAMPLE = pathlib.Path(__file__).parent / "testdata" / "go-rendered-capture.txt"
sample_times, sample_sizes, sample_destinations, _ = capture.parse_tcpdump(
    GO_SAMPLE.read_text()
)
check("parser reads the Go campaign's rendered captures",
      len(sample_times) == 8 and sample_sizes == [1200] * 8
      and len(set(sample_destinations)) == 2)
gaps = twa.interarrivals(sample_times)
check("Go-rendered captures carry a usable cadence",
      len(gaps) == 7 and all(abs(gap - 0.020) < 1e-6 for gap in gaps))

# Kolmogorov-Smirnov runs over inter-arrivals, not raw timestamps, so the
# tests below feed it what the harness feeds it.
steady_times = [0.05 * index for index in range(400)]
steady_gaps = twa.interarrivals(steady_times)
_, p_same = twa.ks_two_sample(steady_gaps, list(steady_gaps))
check("KS accepts identical inter-arrivals", p_same > twa.KS_ALPHA)

doubled_gaps = twa.interarrivals([0.10 * index for index in range(400)])
_, p_shifted = twa.ks_two_sample(steady_gaps, doubled_gaps)
check("KS rejects a doubled interval", p_shifted < twa.KS_ALPHA)

# A small periodic jitter is the case that matters: a blatant difference
# would be visible without statistics at all.
subtle_gaps = twa.interarrivals(
    [0.05 * index + (0.004 if index % 2 else 0.0) for index in range(400)]
)
_, p_subtle = twa.ks_two_sample(steady_gaps, subtle_gaps)
check("KS rejects a subtle periodic shift", p_subtle < twa.KS_ALPHA)

# Regression: heavily tied samples. A fixed-cadence capture yields only a
# handful of distinct float inter-arrivals across thousands of packets, so
# ties are the normal case rather than an edge case. A per-observation ECDF
# walk charges each tie run as a gap and reports a large statistic for a
# sample against itself -- a permanent false alarm on exactly the input this
# harness exists to analyse.
tied = [0.05] * 200 + [0.06] * 200
statistic_tied, p_tied = twa.ks_two_sample(tied, list(tied))
check("KS statistic is zero for a tied sample against itself", statistic_tied == 0.0)
check("KS accepts a tied sample against itself", p_tied > twa.KS_ALPHA)

# ...and the tie handling must not buy that by going blind: a real shift in
# the same tied support still has to be caught.
tied_shifted = [0.05] * 100 + [0.06] * 300
_, p_tied_shifted = twa.ks_two_sample(tied, tied_shifted)
check("KS rejects a shift within a tied support", p_tied_shifted < twa.KS_ALPHA)

# The Kolmogorov survival function is only reached with a positive statistic,
# but its series does not converge as lambda approaches zero, so the
# boundary is asserted directly.
check("Kolmogorov survival at zero is one", twa.kolmogorov_survival(0.0) == 1.0)
check("Kolmogorov survival near zero is one", twa.kolmogorov_survival(0.01) > 0.99)
check("Kolmogorov survival decays", twa.kolmogorov_survival(3.0) < 1e-6)

# Chi-square over destination sequences, taken per sender as labelled counts.
_, p_dest_same = twa.chi_square_counts({"a": 50, "b": 50}, {"a": 50, "b": 50})
check("chi-square accepts identical peer usage", p_dest_same > twa.CHI_SQUARE_ALPHA)
_, p_dest_skew = twa.chi_square_counts({"a": 90, "b": 10}, {"a": 10, "b": 90})
check("chi-square rejects skewed peer usage", p_dest_skew < twa.CHI_SQUARE_ALPHA)

# Per-flow grouping. The registration extracts features per direction and per
# peer; a flow key is exactly that. These cover the defect that made the first
# WAN campaign report a difference on all three hosts: a capture taken with
# "-i any" holds the host's own emissions and its peers', the node is
# restarted between worlds, and the peers' phase relative to the host is
# re-randomised by the restart. Pooled, that shifts the merged inter-arrival
# distribution on its own, whatever the node did.
def flow_capture(spec):
    """Build a parsed-capture tuple from {(src, dst): [times]}."""
    times, sizes, destinations, sources = [], [], [], []
    for (source, destination), stamps in spec.items():
        for stamp in stamps:
            times.append(stamp)
            sizes.append(1200)
            destinations.append(destination)
            sources.append(source)
    return times, sizes, destinations, sources


OWN, PEER = "10.0.0.2.4200", "10.0.0.3.4200"
steady_out = [100.0 + index * 0.05 for index in range(400)]
# Same host, same cadence, but the peer's stream sits at a different phase in
# each world -- which is what restarting the node between worlds produces.
inbound_early = [100.010 + index * 0.05 for index in range(400)]
inbound_late = [100.039 + index * 0.05 for index in range(400)]

grouped = twa.flows_of(flow_capture({(OWN, PEER): steady_out, (PEER, OWN): inbound_early}))
check("flows are keyed by direction and peer", set(grouped) == {(OWN, PEER), (PEER, OWN)})
check("each flow keeps only its own packets", len(grouped[(OWN, PEER)]) == 400)

pooled_a = sorted(steady_out + inbound_early)
pooled_b = sorted(steady_out + inbound_late)
_, pooled_p = twa.ks_two_sample(twa.interarrivals(pooled_a), twa.interarrivals(pooled_b))
check("pooling both directions would raise a false alarm on a phase shift",
      pooled_p < twa.KS_ALPHA)
_, per_flow_p = twa.ks_two_sample(twa.interarrivals(steady_out), twa.interarrivals(steady_out))
check("per-flow analysis is unmoved by the peer's phase",
      per_flow_p > twa.KS_ALPHA)

# Equal-length windows. A capture starts before the node and stops after it,
# so two worlds cover slightly different spans; the count test is registered
# for equal-length windows and must not charge that difference to the node.
long_span = [100.0 + index * 0.05 for index in range(400)]
short_span = [500.0 + index * 0.05 for index in range(396)]
trimmed_left, trimmed_right, width = twa.equal_windows(long_span, short_span, 0.05)
check("equal windows are an integer number of cell intervals",
      abs(width / 0.05 - round(width / 0.05)) < 1e-9)
check("equal windows equalise an honest sender's cell count",
      len(trimmed_left) == len(trimmed_right))
# The window is half-open, so a sender emitting at exactly the nominal
# interval places one cell in each period and none on the closing edge.
check("an honest sender emits one cell per period in the window",
      len(trimmed_right) == round(width / 0.05))

# The instrument must stay sensitive. A fix that stops false alarms by going
# blind is worse than the false alarms, so each difference the registration
# names is re-checked through the per-flow path.
def verdict(world_a, world_b):
    report_failures = []
    left, right, width = twa.equal_windows(sorted(world_a), sorted(world_b), 0.05)
    if len(left) != len(right):
        report_failures.append("count")
    _, p = twa.ks_two_sample(twa.interarrivals(left), twa.interarrivals(right))
    if p < twa.KS_ALPHA:
        report_failures.append("ks")
    if twa.max_burst(left) != twa.max_burst(right):
        report_failures.append("burst")
    return report_failures


check("per-flow path still catches an extra cell",
      "count" in verdict(steady_out, sorted(steady_out + [100.0 + 199 * 0.05 + 0.025])))
check("per-flow path still catches a catch-up burst",
      verdict(steady_out, steady_out[:200] + [110.0 + index * 0.001 for index in range(200)]) != [])
check("per-flow path passes a sender against itself", verdict(steady_out, steady_out) == [])

# Burst detection: a steady 20/second stream and one with a burst must differ.
steady = [index * 0.05 for index in range(100)]
bursty = steady[:50] + [2.5 + index * 0.001 for index in range(50)]
check("burst detection sees a catch-up burst", twa.max_burst(bursty) > twa.max_burst(steady))

# Inter-arrival extraction must be order-independent, since capture order is
# not guaranteed to be sorted.
check("inter-arrivals are order independent",
      twa.interarrivals([3.0, 1.0, 2.0]) == twa.interarrivals([1.0, 2.0, 3.0]))

# The upper regularized gamma must behave at the boundaries it is used at.
check("gamma survival at zero is one", abs(twa.upper_gamma_regularized(1.0, 0.0) - 1.0) < 1e-9)
check("gamma survival decays", twa.upper_gamma_regularized(1.0, 20.0) < 1e-6)

# End to end through main(), with a shim standing in for tcpdump so the exit
# status and report assembly are exercised without a live capture. The
# decision rule is only useful if a failing world actually produces a
# non-zero exit, which is what CI and any operator script keys on.
SHIM = """#!/bin/sh
while [ $# -gt 0 ]; do
  if [ "$1" = "-r" ]; then shift; cat "$1"; exit 0; fi
  shift
done
exit 1
"""


def write_world(path, jitter=0.0, size=1200, inbound_jitter=0.0, inbound=True,
                inbound_drop=0):
    """Render a capture as a host sees it: its own cells out, its peer's in.

    Both directions are present because that is what "-i any" on a real host
    records, and because the measured host is identified as the address that
    both sends and receives. A one-directional fixture would exercise a shape
    the campaign never produces.
    """
    lines = ["reading from file capture.pcap, link-type EN10MB (Ethernet)"]
    for index in range(400):
        stamp = 1712345678.0 + 0.05 * index + (jitter if index % 2 else 0.0)
        lines.append(f"{stamp:.6f} IP 10.0.0.2.4200 > 10.0.0.3.4200: UDP, length {size}")
    if inbound:
        for index in range(400):
            # Loss is modelled by dropping cells from inside the stream rather
            # than by shortening it: a shorter capture is a shorter window, not
            # a difference in behaviour, and the window trimming is right to
            # decline to charge it.
            if inbound_drop and index % inbound_drop == 0 and 0 < index < 399:
                continue
            stamp = 1712345678.013 + 0.05 * index + (inbound_jitter if index % 2 else 0.0)
            lines.append(f"{stamp:.6f} IP 10.0.0.1.4200 > 10.0.0.2.4200: UDP, length 1200")
    path.write_text("\n".join(lines) + "\n")


with tempfile.TemporaryDirectory() as workspace:
    root = pathlib.Path(workspace)
    (root / "tcpdump").write_text(SHIM)
    (root / "tcpdump").chmod(0o755)
    environment = dict(os.environ, PATH=f"{root}{os.pathsep}{os.environ['PATH']}")
    write_world(root / "a", jitter=0.0)
    write_world(root / "b", jitter=0.0)
    write_world(root / "leaky", jitter=0.004)
    write_world(root / "oversized", jitter=0.0, size=1201)
    # Same emissions, a different stream arriving from the peer.
    write_world(root / "lossy-inbound", jitter=0.0, inbound_drop=7)
    write_world(root / "one-way", jitter=0.0, inbound=False)

    analysis = str(pathlib.Path(__file__).with_name("two-world-analysis.py"))

    def run(left, right, *extra):
        return subprocess.run(
            [sys.executable, analysis, str(root / left), str(root / right), "1200", "50",
             *extra],
            env=environment, capture_output=True, text=True,
        ).returncode

    check("end to end: matching worlds exit 0", run("a", "b") == 0)
    check("end to end: a jittered world exits non-zero", run("a", "leaky") == 1)
    check("end to end: an off-size cell exits non-zero", run("a", "oversized") == 1)

    # A difference in what the host received is a fact about the sender or the
    # path, not about this host's scheduler. It must still be reported and must
    # still be non-zero -- silently dropping it would hide a real leak at the
    # sender -- but it must not be returned as this node's verdict.
    check("end to end: a difference on a received flow exits 3, not 1",
          run("a", "lossy-inbound") == 3)

    # Which host a capture was taken at decides which flows the verdict rests
    # on, so a capture that does not say must be refused rather than guessed.
    check("end to end: a one-directional capture fails closed",
          run("one-way", "one-way") == 2)
    check("end to end: an explicit host makes a one-directional capture judgeable",
          run("one-way", "one-way", "10.0.0.2.4200") == 0)

    # A capture the rule cannot read must not be reported as a rejection.
    (root / "unreadable").write_text("this is not a capture at all\n")
    check("end to end: an unreadable capture exits 2, not 1", run("a", "unreadable") == 2)

if failures:
    print(f"\n{len(failures)} self-test(s) failed", file=sys.stderr)
    sys.exit(1)
print("\nall analysis self-tests passed")
